# .github/actions/load-config/action.yml
name: 'Load Workflow Configuration'
description: 'Loads and merges workflow configuration with defaults'
#               CONFIG='${{ steps.load-config.outputs.config }}'
#               NAMESPACE=$(echo "$CONFIG" | jq -r --arg env "${{ inputs.environment }}" \
#               '.environments[$env].namespace // "default"')
#               echo "namespace=$NAMESPACE" >> "$GITHUB_OUTPUT"
inputs:
  defaults-repo:
    description: 'Repository containing default configuration'
    required: false
    default: 'krystof-io/common-workflows'
  defaults-ref:
    description: 'Git ref to use for defaults repository'
    required: false
    default: 'main'
  defaults-path:
    description: 'Path to defaults file in the defaults repository'
    required: false
    default: '.github/workflow-defaults.yml'
  config-path:
    description: 'Path to local configuration file'
    required: false
    default: '.github/workflow.yml'

outputs:
  config:
    description: 'Merged configuration'
    value: ${{ steps.merge-config.outputs.config }}

runs:
  using: "composite"
  steps:
    - name: Checkout defaults repository
      uses: actions/checkout@v4.1.7
      with:
        repository: ${{ inputs.defaults-repo }}
        path: .github/defaults
        ref: ${{ inputs.defaults-ref }}

    - name: Merge configurations
      id: merge-config
      shell: bash
      run: |
        default_file=".github/defaults/${{ inputs.defaults-path }}"
        config_file="${{ inputs.config-path }}"
        
        echo "=== Default Configuration ==="
        cat "${default_file}"
        echo ""
        
        if [ -f "${config_file}" ]; then
          echo "=== Local Configuration ==="
          cat "${config_file}"
          echo ""
        
          echo "=== Merging Configurations ==="
          # Merge default with custom, preferring custom values
          CONFIG=$(yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' \
            "${default_file}" "${config_file}")
        else
          echo "No local configuration found at ${config_file}"
          echo "=== Using Default Configuration ==="
          CONFIG=$(yq eval "${default_file}" -)
        fi
        
        echo "=== Final Merged Configuration ==="
        echo "${CONFIG}"
        echo ""
        
        # Convert to JSON for output
        CONFIG=$(echo "${CONFIG}" | yq eval -o=json -)
        echo "${CONFIG}"
        echo ""
        # Escape potential newlines and special characters for GitHub Actions
        CONFIG="${CONFIG//'%'/'%25'}"
        CONFIG="${CONFIG//$'\n'/'%0A'}"
        CONFIG="${CONFIG//$'\r'/'%0D'}"
        
        echo "config=${CONFIG}" >> "$GITHUB_OUTPUT"