name: Shared Maven Build
on:
  workflow_call:
    outputs:
      generic_image_version:
        description: Generic image version (without hash)
        value: ${{ jobs.build.outputs.generic_image_version }}
      unique_image_version:
        description: Unique image version (with hash)
        value: ${{ jobs.build.outputs.unique_image_version }}
      artifact_version:
        description: Artifact Version (e.g. maven version)
        value: ${{ jobs.build.outputs.artifact_version }}
      artifact_id:
        description: Artifact ID (e.g. maven artifact ID)
        value: ${{ jobs.build.outputs.artifact_id }}
      scm_tag_type:
        description: SCM Tag type (release or snapshot)
        value: ${{ jobs.build.outputs.scm_tag_type }}
      has_snapshot_dependencies:
        description: Whether the project has any SNAPSHOT dependencies
        value: ${{ jobs.build.outputs.has_snapshot_dependencies }}
      is_snapshot:
        description: Whether the project itself is a SNAPSHOT
        value: ${{ jobs.build.outputs.is_snapshot }}
env:
  MAVEN_REPO_URL: ${{ vars.MAVEN_REPO_URL }}
  MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
  MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}

jobs:
  build:
    runs-on: arc-runners-prod
    outputs:
      unique_image_version: ${{ steps.set_build_vars.outputs.unique_image_version }}
      generic_image_version: ${{ steps.set_build_vars.outputs.generic_image_version }}
      artifact_version: ${{ steps.set_build_vars.outputs.artifact_version }}
      artifact_id: ${{ steps.set_build_vars.outputs.artifact_id }}
      scm_tag_type: ${{ steps.set_build_vars.outputs.scm_tag_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [
            {"id": "private-snapshots", "username": "${{ env.MAVEN_REPO_USERNAME }}", "password": "${{ env.MAVEN_REPO_PASSWORD }}"},
            {"id": "private-releases", "username": "${{ env.MAVEN_REPO_USERNAME }}", "password": "${{ env.MAVEN_REPO_PASSWORD }}"},
            {"id": "nexus", "username": "${{ env.MAVEN_REPO_USERNAME }}", "password": "${{ env.MAVEN_REPO_PASSWORD }}"}
            ]
          mirrors: |
            [
            {"id": "nexus", "name":"nexus", "mirrorOf":"*", "url":"${{ env.MAVEN_REPO_URL }}"}
            ]

      - name: Check for SNAPSHOT dependencies
        id: check_snapshots
        run: |
          # Check if project version is SNAPSHOT
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ $PROJECT_VERSION == *-SNAPSHOT ]]; then
            echo "is_snapshot=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_snapshot=false" >> "$GITHUB_OUTPUT"
          fi
          
          # Get dependency tree and check for SNAPSHOTS
          SNAPSHOT_COUNT=$(mvn dependency:list -DexcludeTransitive=true | grep -c SNAPSHOT || true)
          if [ "$SNAPSHOT_COUNT" -gt 0 ]; then
            echo "has_snapshot_dependencies=true" >> "$GITHUB_OUTPUT"
            echo "Found $SNAPSHOT_COUNT SNAPSHOT dependencies:"
            mvn dependency:list -DexcludeTransitive=true | grep SNAPSHOT
          else
            echo "has_snapshot_dependencies=false" >> "$GITHUB_OUTPUT"
            echo "No SNAPSHOT dependencies found"
          fi

      - name: Set up vars
        id: set_build_vars
        run: |
          ARTIFACT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          
          echo "artifact_id=$ARTIFACT_ID" >> "$GITHUB_OUTPUT"
          echo "artifact_version=$ARTIFACT_VERSION" >> "$GITHUB_OUTPUT"
          echo "artifact_id=$ARTIFACT_ID" >> "$GITHUB_ENV"
          echo "artifact_version=$ARTIFACT_VERSION" >> "$GITHUB_ENV"
          
          TAG_NAME=${{ github.ref_name }}

          if [[ "$TAG_NAME" =~ ^[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9]+)?$ ]]; then
            SCM_TAG_TYPE="release"
          else
            SCM_TAG_TYPE="snapshot"
          fi
          
          echo "SCM_TAG_TYPE=$SCM_TAG_TYPE" >> $GITHUB_ENV
          echo "scm_tag_type=$SCM_TAG_TYPE" >> "$GITHUB_OUTPUT"

          UNIQUE_IMAGE_VERSION="$ARTIFACT_VERSION-${GITHUB_SHA::10}"
          GENERIC_IMAGE_VERSION="$ARTIFACT_VERSION"
          
          echo "unique_image_version=$UNIQUE_IMAGE_VERSION" >> "$GITHUB_OUTPUT"
          echo "generic_image_version=$GENERIC_IMAGE_VERSION" >> "$GITHUB_OUTPUT"
          echo "UNIQUE_IMAGE_VERSION=$UNIQUE_IMAGE_VERSION" >> $GITHUB_ENV
          echo "GENERIC_IMAGE_VERSION=$GENERIC_IMAGE_VERSION" >> $GITHUB_ENV

      - name: Logging env
        run: printenv

      - name: Maven Test Build
        run: >
          mvn -f pom.xml clean verify -Dcontainer.image.version=${{env.UNIQUE_IMAGE_VERSION}}
