name: Shared Maven Deploy
on:
  workflow_call:
    inputs:
      unique_image_version:
        type: string
env:
  MAVEN_REPO_URL: ${{ vars.MAVEN_REPO_URL }}
  MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
  MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
  MAVEN_PRIVATE_SNAPSHOT_REPO_URL: ${{ vars.MAVEN_PRIVATE_SNAPSHOT_REPO_URL }}
  MAVEN_PRIVATE_RELEASE_REPO_URL: ${{ vars.MAVEN_PRIVATE_RELEASE_REPO_URL }}
  UNIQUE_IMAGE_VERSION: ${{ inputs.unique_image_version }}
jobs:
  maven-deploy:
    runs-on: arc-runners-prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [
            {"id": "private-snapshots", "username": "${{ env.MAVEN_REPO_USERNAME }}", "password": "${{ env.MAVEN_REPO_PASSWORD }}"},
            {"id": "private-releases", "username": "${{ env.MAVEN_REPO_USERNAME }}", "password": "${{ env.MAVEN_REPO_PASSWORD }}"},
            {"id": "nexus", "username": "${{ env.MAVEN_REPO_USERNAME }}", "password": "${{ env.MAVEN_REPO_PASSWORD }}"}
            ]
          mirrors: |
            [
            {"id": "nexus", "name":"nexus", "mirrorOf":"*", "url":"${{ env.MAVEN_REPO_URL }}"}
            ]

      - name: Maven Repo Deploy
        run: >
          cat ./.m2/settings.xml
          mvn -f pom.xml clean deploy -Dcontainer.image.version=${{env.UNIQUE_IMAGE_VERSION}} \
            -DskipTests=true \
            -DaltSnapshotDeploymentRepository=private-snapshots::${{env.MAVEN_PRIVATE_SNAPSHOT_REPO_URL}} \
            -DaltReleaseDeploymentRepository=private-releases::${{env.MAVEN_PRIVATE_RELEASE_REPO_URL}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.UNIQUE_IMAGE_VERSION}}.jar
          path: target/*.jar
          retention-days: 1