name: Shared Maven Deploy
on:
  workflow_call:
    inputs:
      generic_image_version:
        type: string
      unique_image_version:
        type: string
      dockerfile_tag:
        type: string
        default: 'HEAD'
      dockerfile_directory:
        type: string
env:
    IMAGE_REGISTRY_HOST: ${{ vars.IMAGE_REGISTRY_HOST }}
    IMAGE_REGISTRY_USERNAME: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
    IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
    UNIQUE_IMAGE_VERSION: ${{ inputs.unique_image_version }}
    GENERIC_IMAGE_VERSION: ${{ inputs.generic_image_version }}
    DOCKERFILE_TAG: ${{ inputs.dockerfile_tag }}
    DOCKERFILE_DIRECTORY: ${{ inputs.dockerfile_directory }}
jobs:
  image-build:
    runs-on: arc-runners-prod

    steps:
      - name: Logging env
        run: printenv

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Download build artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{env.UNIQUE_IMAGE_VERSION}}.jar
          path: target

      - name: Login to internal private docker repo
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY_HOST}}
          username: ${{ env.IMAGE_REGISTRY_USERNAME }}
          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

      - name: Download Dockerfile
        uses: actions/checkout@v4.1.7
        with:
          repository: krystof-io/docker-files
          ref: ${{ env.DOCKERFILE_TAG }}
          path: dockerfile

#      - name: Login to internal docker proxy
#        uses: docker/login-action@v3
#        with:
#          registry: docker-proxy.krystof.io
#          username: ${{ env.IMAGE_REGISTRY_USERNAME }}
#          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: ls -lRt && docker build \
          -t ${{ env.IMAGE_REGISTRY_HOST}}/${{github.repository}}:${{ env.UNIQUE_IMAGE_VERSION }} -f ./dockerfile/${{ env.DOCKERFILE_DIRECTORY }}/Dockerfile .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_REGISTRY_HOST}}/${{github.repository}}:${{ env.UNIQUE_IMAGE_VERSION }}

      - name: Tag Docker image with generic version tag
        run: |
          docker tag ${{ env.IMAGE_REGISTRY_HOST}}/${{github.repository}}:${{ env.UNIQUE_IMAGE_VERSION }} \
            ${{ env.IMAGE_REGISTRY_HOST}}/${{github.repository}}:${{ env.GENERIC_IMAGE_VERSION }}
          docker push ${{ env.IMAGE_REGISTRY_HOST}}/${{github.repository}}:${{ env.GENERIC_IMAGE_VERSION }}
