run-name: Deploy to ${{inputs.target_env}}
on:
  workflow_call:
jobs:
  build:
    uses: krystof-io/common-workflows/.github/workflows/shared-maven-build.yaml@main
    secrets: inherit
  sonar-scan:
    needs: build
    uses: krystof-io/common-workflows/.github/workflows/shared-sonar-scan.yaml@main
    secrets: inherit
  maven-deploy:
    uses: krystof-io/common-workflows/.github/workflows/shared-maven-deploy.yaml@main
    needs: [build, sonar-scan]
    secrets: inherit
    with:
      unique_image_version: ${{ needs.build.outputs.unique_image_version }}
  image-build:
    uses: krystof-io/common-workflows/.github/workflows/shared-image-build.yaml@main
    needs: [build, maven-deploy]
    secrets: inherit
    with:
      generic_image_version: ${{ needs.build.outputs.generic_image_version }}
      unique_image_version: ${{ needs.build.outputs.unique_image_version }}
  deploy-app:
    uses: krystof-io/common-workflows/.github/workflows/shared-deploy-app.yaml@main
    needs: [build, image-build]
    secrets: inherit
    with:
      generic_image_version: ${{ needs.build.outputs.generic_image_version }}
      unique_image_version: ${{ needs.build.outputs.unique_image_version }}
      artifact_id: ${{ needs.build.outputs.artifact_id }}
      scm_tag_type: ${{ needs.build.outputs.scm_tag_type }}
