run-name: DU Prod Deploy
on:
  workflow_call:
    inputs:
      image_version:
        type: string

jobs:
  setup:
    runs-on: arc-runners-prod
    outputs:
      artifact_id: ${{ steps.set_build_vars.outputs.artifact_id }}
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up vars
        id: set_build_vars
        run: |
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "artifact_id=$ARTIFACT_ID" >> "$GITHUB_OUTPUT"

  deploy-prod:
    runs-on: arc-runners-prod
    needs: setup
    secrets: inherit
    uses: krystof-io/common-workflows/.github/workflows/shared-deploy-app-to-env-fluxcd.yaml@main
    with:
      target_env: prod
      target_app_name: ${{ needs.setup.outputs.artifact_id }}
      image_version: ${{ github.event.inputs.image_version }}