run-name: Node Frontend Build
on:
  workflow_call:
    inputs:
      image_version:
        type: string
env:
  IMAGE_REGISTRY_HOST: ${{ vars.IMAGE_REGISTRY_HOST }}
  IMAGE_REGISTRY_USERNAME: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

jobs:
  setup:
    runs-on: arc-runners-prod
    outputs:
      project_name: ${{ steps.get-project-name.outputs.project_name }}
    steps:
      - uses: actions/checkout@v4.1.7

      - id: get-project-name
        name: Get project name from package.json
        run: |
          PROJECT_NAME=$(jq -r '.name' package.json)
          echo "project_name=$PROJECT_NAME" >> "$GITHUB_OUTPUT"
          echo "Project name determined: $PROJECT_NAME" >> $GITHUB_STEP_SUMMARY

  image-verification:
    runs-on: arc-runners-prod
    needs: setup
    steps:

      - name: Login to internal private docker repo
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY_HOST}}
          username: ${{ env.IMAGE_REGISTRY_USERNAME }}
          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

      - name: Validate Image Tag
        run: |
          IMAGE_TAG=${{ github.event.inputs.image_version }}
          IMAGE_REGISTRY=${{ env.IMAGE_REGISTRY_HOST }}
          if ! docker manifest inspect $IMAGE_REGISTRY/${{ github.repository }}:$IMAGE_TAG > /dev/null; then
            echo "Error: Image tag $IMAGE_TAG does not exist in the registry $IMAGE_REGISTRY."
            exit 1
          fi

  deploy-prod:
    needs: [setup, image-verification]
    secrets: inherit
    uses: krystof-io/common-workflows/.github/workflows/shared-deploy-app-to-env-fluxcd.yaml@main
    with:
      target_env: prod
      target_app_name: ${{ needs.setup.outputs.project_name }}
      image_version: ${{ github.event.inputs.image_version }}
