run-name: DU Branch Build
on:
  workflow_call:
jobs:
  setup:
    runs-on: arc-runners-prod
    outputs:
      config: ${{ steps.load-config.outputs.config }}
    steps:
      - uses: actions/checkout@v4.1.7

      - id: load-config
        uses: krystof-io/common-workflows/.github/actions/load-config@main

  build:
    uses: krystof-io/common-workflows/.github/workflows/shared-maven-build.yaml@main
    needs: setup
    secrets: inherit
#  maven-deploy:
#    uses: krystof-io/common-workflows/.github/workflows/shared-maven-deploy.yaml@main
#    needs: [build, sonar-scan]
#    secrets: inherit
#    with:
#      unique_image_version: ${{ needs.build.outputs.unique_image_version }}
  image-build:
    uses: krystof-io/common-workflows/.github/workflows/shared-image-build.yaml@main
    needs: [build, maven-deploy]
    secrets: inherit
    with:
      generic_image_version: ${{ needs.build.outputs.generic_image_version }}
      unique_image_version: ${{ needs.build.outputs.unique_image_version }}
  sonar-scan:
    needs: build
    uses: krystof-io/common-workflows/.github/workflows/shared-sonar-scan.yaml@main
    secrets: inherit
  deploy-app:
    uses: krystof-io/common-workflows/.github/workflows/shared-deploy-app.yaml@main
    needs: [build, image-build]
    secrets: inherit
    with:
      generic_image_version: ${{ needs.build.outputs.generic_image_version }}
      unique_image_version: ${{ needs.build.outputs.unique_image_version }}
      artifact_id: ${{ needs.build.outputs.artifact_id }}
      scm_tag_type: ${{ needs.build.outputs.scm_tag_type }}
