run-name: Shared Library Tag
on:
  workflow_call:
jobs:
  setup:
    runs-on: arc-runners-prod
    outputs:
      config: ${{ steps.load-config.outputs.config }}
    steps:
      - uses: actions/checkout@v4.1.7

      - id: load-config
        uses: krystof-io/common-workflows/.github/actions/load-config@main
        with:
          defaults-path: '.github/workflow-defaults-shared-library.yml'

      - id: set-outputs
        name: Set outputs
        run: |
            CONFIG='${{ steps.load-config.outputs.config }}'
  sonar-scan:
    needs: setup
    uses: krystof-io/common-workflows/.github/workflows/shared-sonar-scan.yaml@main
    secrets: inherit
  build:
    uses: krystof-io/common-workflows/.github/workflows/shared-maven-build.yaml@main
    needs: build
    secrets: inherit
