run-name: Node Frontend Build
on:
  workflow_call:
jobs:
  setup:
    runs-on: arc-runners-prod
    outputs:
      config: ${{ steps.load-config.outputs.config }}
      dockerfile_repo_dir: ${{ steps.set-outputs.outputs.dockerfile_repo_dir }}
      dockerfile_github_ref: ${{ steps.set-outputs.outputs.dockerfile_github_ref }}
      generic_image_version: ${{ steps.get-version.outputs.generic_image_version }}
      unique_image_version: ${{ steps.get-version.outputs.unique_image_version }}
      project_name: ${{ steps.get-project-name.outputs.project_name }}
    steps:
      - uses: actions/checkout@v4.1.7

      - id: load-config
        uses: krystof-io/common-workflows/.github/actions/load-config@main
        with:
          defaults-path: '.github/workflow-defaults-node-frontend.yml'

      - id: set-outputs
        name: Set outputs
        run: |
            CONFIG='${{ steps.load-config.outputs.config }}'
          
            DOCKER_FILE_REPO_DIR=$(echo "$CONFIG" | jq -r '.dockerFileRepoDir // "deployment-unit"')
            echo "dockerfile_repo_dir=$DOCKER_FILE_REPO_DIR" >> "$GITHUB_OUTPUT"
            
            DOCKER_FILE_GITHUB_REF=$(echo "$CONFIG" | jq -r '.dockerFileGithubRef // "main"')
            echo "dockerfile_github_ref=$DOCKER_FILE_GITHUB_REF" >> "$GITHUB_OUTPUT"

      - id: get-version
        name: Get version from package.json
        run: |
          VERSION=$(jq -r '.version' package.json)
                    
          UNIQUE_IMAGE_VERSION="$VERSION-${GITHUB_SHA::10}"
          GENERIC_IMAGE_VERSION="$VERSION"
          echo "Generic Image Version: $GENERIC_IMAGE_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "Unique  Image Version: $UNIQUE_IMAGE_VERSION" >> $GITHUB_STEP_SUMMARY
          
          echo "unique_image_version=$UNIQUE_IMAGE_VERSION" >> "$GITHUB_OUTPUT"
          echo "generic_image_version=$GENERIC_IMAGE_VERSION" >> "$GITHUB_OUTPUT"
          echo "UNIQUE_IMAGE_VERSION=$UNIQUE_IMAGE_VERSION" >> $GITHUB_ENV
          echo "GENERIC_IMAGE_VERSION=$GENERIC_IMAGE_VERSION" >> $GITHUB_ENV

      - id: get-project-name
        name: Get project name from package.json
        run: |
          PROJECT_NAME=$(jq -r '.name' package.json)
          echo "project_name=$PROJECT_NAME" >> "$GITHUB_OUTPUT"

  image-build:
    uses: krystof-io/common-workflows/.github/workflows/shared-image-build.yaml@main
    needs: [setup]
    secrets: inherit
    with:
      generic_image_version: ${{ needs.setup.outputs.generic_image_version }}
      unique_image_version: ${{ needs.setup.outputs.unique_image_version }}
      dockerfile_tag: ${{ needs.setup.outputs.dockerfile_github_ref }}
      dockerfile_directory: ${{ needs.setup.outputs.dockerfile_repo_dir }}
      app_type: node

  deploy-dev:
    if: ${{ github.ref_type == 'branch' || github.ref_type == 'tag' }}
    uses: krystof-io/common-workflows/.github/workflows/shared-deploy-app-to-env-fluxcd.yaml@main
    needs: [build, image-build]
    secrets: inherit
    with:
      target_env: dev
      target_app_name: ${{ needs.setup.outputs.project_name }}
      image_version: ${{ needs.setup.outputs.unique_image_version }}
